name: build package
on: [ push ]
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v6
                        - name: WoltLab Suite Package Creation
                          uses: KittMedia/action-wsc-package-create@main
                        - uses: actions/upload-artifact@v7
                          with:
                                  archive: 'false'
                                  name: ${{ github.event.repository.name }}.tar.gz
                                  path: ${{ github.event.repository.name }}.tar.gz
